### ISSUE TITLE
Add secondary tag_num/tag_type to output

### ISSUE THREAD

**Issue by tristan-sebens** [tristan-sebens/metl#100]
Katy has requested that the secondary tag_num/tag_type fields be added the TAG table and `metl` output. Both fields will be supplied by the user via the `meta` parameter.

These fields will also need to be added to the TAG table constraints which reference the RELEASE/RECOVERY table.

More research will be needed to determine if it is possible to add these fields to the table constraint, as they are not part of the primary keys of RELEASE or RECOVERY

**Comment by kechave** [comment]
Note that these will not be required...as some etags don't have a secondary tag type.

**Comment by tristan-sebens** [comment]
Cannot add the constraint to the table, as the foreign key constraints used for this reference the primary key of a table. Secondary tag numbers and types are not a part of the compound primary keys for either the RELEASE or RECOVERY table, and so the constraint cannot be enforced.

Can still add the fields to the TAG table and have them passed in by the user via the `meta` parameter

**Comment by tristan-sebens** [comment]
Added secondary tag num and type fields to pipeline. User specifies values in `meta` parameter. Fields are required to be present, even if provided values are blank.

Updated README to reflect new requirements.
