### ISSUE TITLE
Zeros when data is loaded successfully

### ISSUE THREAD

**Issue by KevinSiwicke-NOAA** [tristan-sebens/metl#103]
I was able to load a Lotek 1000-1250 (#4066), and the data appeared in the tag table and the instant table. However the readout in R was:

Data inserted into DB succesfully.
Row counts:
 - TAG: 0
 - TAG_DATA_INSTANT: 0
 - TAG_FIELD_METADATA: 0

Makes it seem like there was nothing there.

**Comment by tristan-sebens** [comment]
Could not reproduce issue. 

Cleared data from DB, then successfully re-uploaded data from Lotek tag 4066. Output:

```
Data inserted into DB succesfully.
Row counts:
 - TAG: 1
 - TAG_DATA_INSTANT: 44806
 - TAG_FIELD_METADATA: 88
```

More information needed to understand root cause of users issue.
