### ISSUE TITLE
better error explanations

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#107]
Not sure if this possible, but some explanation for certain errors would be super helpful. For example - 1) tag does not exist in database, etc....

**Comment by tristan-sebens** [comment]
Our ability to implement this is limited, as the constraints are implemented by the DB, but errors are handled by the R process, and the degree to which they talk to eachother is limited. However, I was able to find a decent solution by changing the way that the R code *displays* the errors which are sent back by the DB, such that the name of the constraint which was violated becomes visible. I then renamed all of the constraints to more meaningful and descriptive names. Now when a DB constraint is violated, it looks something like this:



![Image](https://github.com/user-attachments/assets/8a564872-f288-4b26-a176-c00a322518fe)

Which provides substantially more information to the user about the nature of the error. Hopefully this helps things.
