### ISSUE TITLE
Consistent Field Naming

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#114]
I see that you have renamed the tables in the database. Thanks!

Now we need to make sure that column headings are consistent...particularly to match what is in the Release and Recovery Tables....or everything will break. An example that briefly caught my eye: SEC_TAG_TYPE and SEC_TAG_NUM.

**Comment by tristan-sebens** [comment]
Staging this to be completed last in release 0.4 bc it will require changes to the DB that will break the currently supported release. 

DB change will need to be synchronized with package update.
