### ISSUE TITLE
DATA_OWNER table

### ISSUE THREAD

**Issue by tristan-sebens** [tristan-sebens/metl#29]
1. This table can be deleted.
2. With this, this field can be deleted in the 'Input Form.' This will be included in the Metadata Table, and there is no way to predict who 'Data Owners' will be in the future.

**Comment by tristan-sebens** [comment]
I would actually advise against this decision. 

With regards to not being able to predict future owners, this should not be a problem, as new owners will be able to enter themselves into the DATA_OWNERS table from the metadata input form simply by typing their name instead of selecting one of the existing names. 

Additionally, it is well established best practice within database design that entities which have a many to one relationship (i.e. each data owner can own multiple tags) that a separate table be used to list both entities and that they be linked with lookup keys. This allows for future changes to be made while minimizing the number of records which must be altered.

**Comment by kechave** [comment]
Good argument but I'm going to stand with this removing this table. Listed Data Owners are only in the metadata. These are all fillable, unconventional type of fields. Not really 'data' but reference information.
