### ISSUE TITLE
Identification of miniPAT tags

### ISSUE THREAD

**Issue by jknielsen** [tristan-sebens/metl#33]
Lines 209 - 222 in identifier_config.R. Sometimes miniPATs have the Orientation.csv as well (if they have been deployed for 90 days or less). Also, for the files that should be present, do they all need to be there for the identification? Sometimes, depending on how the tag is programmed, some of those files won't be present - or sometimes not enough data are transmitted to make a certain type of file.

**Comment by tristan-sebens** [comment]
Hi Julie,

It looks like the MiniPAT Identifier object currently looks for the explicit _absence_ of an Orientation.csv file. Thanks for bringing this to my attention. I'll alter the `identify` function to adjust for this. 

Would you be able to supply me with an example data directory from a MiniPAT which generated an `Orientation.csv` file?
