### ISSUE TITLE
Input Form is bringing up the wrong tag make/model/type

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#38]
Th Input Form doesn't bring up the correct Make/Model for the associated tag that is listed.

**Comment by tristan-sebens** [comment]
After a meeting, it was determined that this was happening for two Lotek 1400 tags, 9319 and 11265.

**Comment by tristan-sebens** [comment]
Two additional tags found with unusual formatting: 7814 and 9256. 

All four files have different formatting, which suggests to me that they have all been altered from their original output format. Requested that the raw data files be re-processed so we can check the output formats.

**Comment by tristan-sebens** [comment]
I reached out to Lotek support to inquire after this data format. I'll update here when I hear back.

**Comment by tristan-sebens** [comment]
InputFields and InputForm are no longer used.
