### ISSUE TITLE
Error: Data files not recognized - Lotek 1300 tag

### ISSUE THREAD

**Issue by KevinSiwicke-NOAA** [tristan-sebens/metl#49]
I have a my directory setup where in the directory is a folder "5728" and in that folder are two files, the day log and the regular log. I'm not sure how this is supposed to be seyup, but I'm getting an error related to my directory:

The selected directory does not show the structure expected by the selected Decoder:

Day log file missing
Regular log file missing
Error in decode(...) : 
  The selected directory does not contain the necessary data to proceed.
In addition: Warning message:
In decode(...) : 

Uploaded files are in a folder "5728" which is in the data directory folder.

[LTD1300D5728_Day log.csv](https://github.com/user-attachments/files/15959901/LTD1300D5728_Day.log.csv)
[LTD1300D5728_Regular log.csv](https://github.com/user-attachments/files/15959902/LTD1300D5728_Regular.log.csv)

**Comment by tristan-sebens** [comment]
Hi Kevin, I'm having trouble reproducing your issue. When I download the files you uploaded into a folder, and then attempt to decode that folder the package extracts the data successfully.

The package is clearly not identifying the files in the directory as being in the correct location/format. A couple of thoughts:
- Are the files correctly named? They should follow the pattern: LTD1300D5728_Day Log.csv and LTD1300D5728_Regular Log.csv, respectively. The links you provided do appear to be correctly named, but it would be worth making sure the files on disk follow the same naming pattern.
- Are the files in the root of the selected directory? Is it possible that the directory selected for processing has a subdirectory in it which contains the data files?

**Comment by KevinSiwicke-NOAA** [comment]
Those are the exact files/names I have. I followed the previous iteration by having a subdirectory that was the tag number, so in this case ("5728"). I didn't see any guidance on folder structure, so perhaps that is wrong. When I point directly to the folder containing those two files, I get this error:
"Error in if (lengths(fps) > 1) { : argument is of length zero"

So either way throws an error.

**Comment by tristan-sebens** [comment]
Hey Kevin, just checking: it seemed like in the meeting today you we perhaps able to upload this directory successfully. Was that the case? Was the issue that the package was trying to decode the parent directory, rather than the data directory?

**Comment by KevinSiwicke-NOAA** [comment]
Yes, the directory issue was sorted and your updates removed the "Error in if (lengths(fps) > 1) { : argument is of length zero" that was occurring. You can close this.
