### ISSUE TITLE
error writing to table

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#60]
Same code and data as issue #59 (except I did fix the tag_num)

Error in value[[3L]](cond) : 
  Error creating temporary table TAG_temp_FRlyRkvkczSn: Can't copy data to table "TAG_temp_FRlyRkvkczSn".

**Comment by tristan-sebens** [comment]
Hi Cindy,

This was determined to be caused by an out-of-date `odbc` package. `metl` requires `odbc` >= 1.4.2.

Update the package and this issue should resolve. Let me know if you still have issues.
