### ISSUE TITLE
Add character timestamps to the outputs

### ISSUE THREAD

**Issue by tristan-sebens** [tristan-sebens/metl#67]
It could be advantageous for the users to be able to read the output timestamps in plain character timestamps. As such, it could be worth adding independent fields to the output FieldMap objects which generate these timestamps. 

However, doing so will require that a timezone be specified. This would require that either the user specify such a timezone, or one be hardcoded into the system. 

If one is hardcoded, it makes the most sense for this to be either UTC or AKST. Either way, it is paramount that the timezone be explicitly notated in the timestamp field itself.

**Comment by CindyTribuzio-NOAA** [comment]
This could be one of the required metadata fields. We do need a converted timestamp field the is meaningful

**Comment by tristan-sebens** [comment]
At this point, I think the best way to implement this will be to add an independent Field to the output FieldMaps which automatically generates the converted timestamps using the `as.POSIXct` function. By omitting the `tz` (timezone) parameter, the function will default to the timezone of the computer the command is being executed on, which should be the desired timezone for the average user. Importantly, these character timestamps must explicitly note the timezone in which they are expressed.

The character timestamp will always be accompanied by the POSIXct timestamp for posterity and accuracy.

**Comment by tristan-sebens** [comment]
Updated code-base to automatically generate character timestamps from the POSIXct timestamps. Changes have been added to the `0.1.1` release.

Doing this required altering the field names of the POSIXct timestamps, so the corresponding ABLTAG fields will need to be updated as well.
