### ISSUE TITLE
Initial set up and use cases documentation

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#75]
Installation
- Add some version information. What are the minimum requirements? Especially regarding db connections

Use case 1
- Suggest adding some explanation of the folder hierarchy for tag data, e.g., only one tag at a time, folder can’t have subfolders.
- The db_conn code in the Example 1 instructions does not work for me
db_conn = 
  DBI::dbConnect(
    odbc::odbc(),
    Driver="{Oracle in instantclient_19_18}",
    Dbq="AFSC",
    UID = abltag_username, # --- Username
    PWD = abltag_password  # --- Password
  )

This does work
db_conn <- dbConnect(odbc::odbc(), dsn = "AFSC", uid = "abltag", 
                 pwd = .........)
- Need to include the decoder = metl::decoders$Decoder_StarOddi_DST to the initiate extraction steps
- Add a complete end to end example code for metl in use for abltag. Include an overly descriptive description of the example, a total hand holder.
- Suggest a list of common trouble shooting tips

Use case 2
- Add information and examples on how to access specific fields
- Are these three objects the only available objects?
- I was able to view instant_data, but only got NULL when I tried to view summary_data for the testing tag ET5728

Use case 3
- Same comments as above.

**Comment by tristan-sebens** [comment]
Updated README documentation to include suggested changes
