### ISSUE TITLE
DST-milliF - no decoder option

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#84]
There is no decoder option to detect Star Oddi_DST_milli F tags.

**Comment by tristan-sebens** [comment]
StarOddi DST milli-F tags use the same Decoder as the StarOddi DST tags. 

I'll update the decoder list so that there is an entry for DST milli-F, and it will simply reference the DST Decoder

**Comment by tristan-sebens** [comment]
Added StarOddi DST milli-F entry to the `decoders` list. Entry simply points to StarOddi DST `Decoder`
