### ISSUE TITLE
Lotek tags sensor data - variable units

### ISSUE THREAD

**Issue by tristan-sebens** [tristan-sebens/metl#94]
It appears that the Lotek 1000-1250 tag data can report its sensor data in either standard units (PSI, deg C, etc) or in raw sensor values (eg. 2231). This is confusing to the package, as it interprets all values as being in standard units.

Example of sensor value output: Sablefish - 3925, Sablefish - 3968

Example of standard units output: Literally everything else

Determine if this is a systemic problem or limited to these files, and take appropriate action.

**Comment by kechave** [comment]
Where are you getting this data? I don't see them in the Google Drive.

We can ignore these tags...probably something fishy with the data collection.

**Comment by tristan-sebens** [comment]
I agree. After looking through the data, I was only able to find two instances of this, which makes me think it's a one-off issue and not systemic.
